# RabbitMQ docker-compose file
version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672' # Message broker
      - '15672:15672' # Web UI
    volumes:
      - rabbitmq_data